/* ============================================================================
   ДАННЫЕ КОМПАНИЙ — РЕДАКТИРУЙТЕ ТОЛЬКО ЭТОТ ФАЙЛ
   ============================================================================
   100 крупнейших фармацевтических компаний с производством или присутствием
   в России. Чтобы добавить компанию — скопируйте любой блок { ... } ниже,
   вставьте в конец списка перед закрывающей ] и замените значения.
   Ничего в коде сайта (index.html) менять не нужно: фильтры, карта,
   аналитика, сравнение и экспорт обновятся автоматически.

   ПОЯСНЕНИЯ К ПОЛЯМ:
   - name            : краткое название (показывается на карточке)
   - marketRank      : позиция в рейтинге Forbes 2025 (необязательно)
   - fullName        : полное юридическое / официальное название
   - country         : "РФ" | "Зарубеж" | "СП" (совместное предприятие)
   - status          : короткий статус-ярлык (виден в шапке карточки)
   - hasProductionInRussia : true / false — есть ли завод/локализация в РФ
   - regions         : [ "Регион", ... ] — субъекты РФ присутствия
   - factories       : заводы. lat/lng — координаты (уровень города) для карты.
                       gmp: "Да" | "Нет" | "н/д"
   - employeesRussia : число сотрудников в РФ (или "н/д")
   - employeesGlobal : глобально (или "н/д")
   - revenue         : выручка в РФ, млрд ₽ (число; null если не раскрыта)
   - revenueYear     : за какой год выручка
   - yearEnteredRussia : год прихода / основания в РФ
   - segments        : ["Дженерики","Оригинальные","Биотех","Вакцины","OTC","Рецептурные"]
   - therapeuticAreas: ["Онкология","Кардиология", ...]
   - keyProducts     : ["Препарат", ...]
   - hasRnD          : true / false — есть ли R&D в РФ
   - hr              : { roles:[...], careerSite:"url", note:"строка" }
   - website         : сайт компании
   - logoColor       : цвет плашки логотипа (любой hex), буквы возьмутся из name
   - note            : произвольная заметка (новости/события), можно ""

   Где данные публично не раскрыты — стоит "н/д" или null. Это честно;
   выдуманные цифры не приводятся. Координаты заводов приблизительны.
   ============================================================================ */

window.PHARMA_COMPANIES = [
  /* ===================== РОССИЙСКИЕ КОМПАНИИ ===================== */
  {
    name: "Озон Фармацевтика",
    marketRank: 1,
    fullName: "АО «Озон Фармацевтика»",
    country: "РФ",
    status: "Российская · публичная (MOEX)",
    hasProductionInRussia: true,
    regions: ["Самарская область"],
    factories: [
      { city: "Жигулёвск", lat: 53.4106, lng: 49.4969, products: "Дженерики, твёрдые лекарственные формы", gmp: "Да" },
      { city: "Тольятти (ОЭЗ)", lat: 53.5078, lng: 49.4204, products: "Современные ЛП, расширение мощностей", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: 63.6,
    revenueYear: 2025,
    yearEnteredRussia: 2001,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Кардиология", "Неврология", "Онкология (в разработке)", "Широкий профиль"],
    keyProducts: ["556 регистрационных удостоверений", "Портфель дженериков"],
    hasRnD: true,
    hr: { roles: ["Производство", "QC/QA", "Регистрация", "R&D"], careerSite: "https://ozonpharm.ru/", note: "Пайплайн 244 молекулы; планы по биопрепаратам" },
    website: "https://ozonpharm.ru/",
    logoColor: "#2563eb",
    note: "№1 в рейтинге Forbes по итогам 2025 года. IPO в 2024 году."
  },
  {
    name: "Биннофарм Групп",
    marketRank: 2,
    fullName: "ООО «Биннофарм Групп» (АФК «Система»)",
    country: "РФ",
    status: "Российская · группа АФК «Система»",
    hasProductionInRussia: true,
    regions: ["Москва", "Московская область", "Ставропольский край", "Курганская область", "Республика Татарстан"],
    factories: [
      { city: "Зеленоград (Москва)", lat: 55.9825, lng: 37.1814, products: "Биотех, готовые лекарственные формы", gmp: "Да" },
      { city: "Ставрополь", lat: 45.0445, lng: 41.9690, products: "Твёрдые и жидкие формы", gmp: "Да" },
      { city: "Курган", lat: 55.4500, lng: 65.3333, products: "Инфузионные растворы, ампулы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: 54.0,
    revenueYear: 2025,
    yearEnteredRussia: 2001,
    segments: ["Дженерики", "Биотех", "Рецептурные", "OTC"],
    therapeuticAreas: ["Антибиотики", "Неврология", "Кардиология", "Иммунология"],
    keyProducts: ["Портфель >450 препаратов", "Вакцины (исторически)"],
    hasRnD: true,
    hr: { roles: ["Производство", "Медпредставители", "QA/QC", "Регистрация"], careerSite: "https://binnopharm-group.ru/", note: "49 регистрационных удостоверений за 2025 г. в 11 странах" },
    website: "https://binnopharm-group.ru/",
    logoColor: "#0891b2",
    note: "№2 в рейтинге Forbes 2025. Включает «Алиум», «Биоком», «Синтез»."
  },
  {
    name: "Отисифарм",
    marketRank: 3,
    fullName: "ПАО «Отисифарм»",
    country: "РФ",
    status: "Российская · публичная",
    hasProductionInRussia: true,
    regions: ["Калининградская область"],
    factories: [
      { city: "Храброво (Калининград)", lat: 54.8900, lng: 20.5926, products: "OTC-препараты, готовые формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: 54.8,
    revenueYear: 2025,
    yearEnteredRussia: 2013,
    segments: ["OTC"],
    therapeuticAreas: ["Простуда и грипп", "Гастроэнтерология", "Витамины"],
    keyProducts: ["Арбидол", "Амиксин", "Компливит", "Пенталгин"],
    hasRnD: false,
    hr: { roles: ["Маркетинг", "Производство", "Продажи"], careerSite: "https://otcpharm.ru/", note: "Открыли собственное производство в Калининграде в 2023 г." },
    website: "https://otcpharm.ru/",
    logoColor: "#7c3aed",
    note: "Крупнейший российский производитель безрецептурных препаратов."
  },
  {
    name: "Фармстандарт",
    marketRank: 4,
    fullName: "ПАО «Фармстандарт»",
    country: "РФ",
    status: "Российская · группа",
    hasProductionInRussia: true,
    regions: ["Курская область", "Уфа (Башкортостан)", "Тюменская область", "Московская область"],
    factories: [
      { city: "Курск", lat: 51.7373, lng: 36.1874, products: "Готовые лекарственные формы", gmp: "Да" },
      { city: "Уфа", lat: 54.7388, lng: 55.9721, products: "Препараты, фактор свёртывания крови VIII", gmp: "Да" },
      { city: "Тюмень", lat: 57.1530, lng: 65.5343, products: "Таблетки, капсулы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: 52.2,
    revenueYear: 2025,
    yearEnteredRussia: 1996,
    segments: ["Дженерики", "Биотех", "OTC", "Рецептурные"],
    therapeuticAreas: ["Эндокринология", "Гематология", "Неврология", "Широкий профиль"],
    keyProducts: ["Арбидол", "Компливит", ">400 препаратов, >140 в ЖНВЛП"],
    hasRnD: true,
    hr: { roles: ["Производство", "QA/QC", "R&D", "Логистика"], careerSite: "https://pharmstd.ru/", note: "Запуск производства фактора VIII (2024). Завод плазмы в «Алабушево» в планах." },
    website: "https://pharmstd.ru/",
    logoColor: "#dc2626",
    note: "Один из исторических лидеров; мощности >1,7 млрд упаковок в год."
  },
  {
    name: "Биокад",
    marketRank: 5,
    fullName: "АО «БИОКАД»",
    country: "РФ",
    status: "Российская · биотех полного цикла",
    hasProductionInRussia: true,
    regions: ["Санкт-Петербург", "Москва (Зеленоград)", "Московская область"],
    factories: [
      { city: "Стрельна (СПб)", lat: 59.8500, lng: 30.0333, products: "Моноклональные антитела, биопрепараты", gmp: "Да" },
      { city: "Зеленоград (Москва)", lat: 55.9825, lng: 37.1814, products: "Биотехнологическое производство", gmp: "Да" }
    ],
    employeesRussia: 2700,
    employeesGlobal: 2700,
    revenue: 52.2,
    revenueYear: 2025,
    yearEnteredRussia: 2001,
    segments: ["Биотех", "Оригинальные", "Вакцины"],
    therapeuticAreas: ["Онкология", "Аутоиммунные", "Инфекционные"],
    keyProducts: ["~55–62 препарата", "Оригинальные моноклональные антитела"],
    hasRnD: true,
    hr: { roles: ["Учёные/R&D (~40%)", "Биопроизводство", "Клинические исследования"], careerSite: "https://biocad.ru/career", note: "~40% штата — учёные и исследователи. Полный цикл: от молекулы до производства." },
    website: "https://biocad.ru/",
    logoColor: "#059669",
    note: "Один из ведущих биотех-игроков РФ. Офисы в ОАЭ, Бразилии, Вьетнаме, Китае."
  },
  {
    name: "Фармасинтез",
    marketRank: 6,
    fullName: "АО «Фармасинтез»",
    country: "РФ",
    status: "Российская · группа",
    hasProductionInRussia: true,
    regions: ["Иркутская область", "Санкт-Петербург", "Тюменская область", "Приморский край"],
    factories: [
      { city: "Иркутск", lat: 52.2870, lng: 104.3050, products: "Противотуберкулёзные, ВИЧ, онкология", gmp: "Да" },
      { city: "Санкт-Петербург", lat: 59.9343, lng: 30.3351, products: "Готовые формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: 36.2,
    revenueYear: 2025,
    yearEnteredRussia: 1997,
    segments: ["Дженерики", "Рецептурные", "Оригинальные"],
    therapeuticAreas: ["Фтизиатрия (ТБ)", "ВИЧ", "Онкология", "Эндокринология"],
    keyProducts: ["Противотуберкулёзные препараты", "Антиретровирусные"],
    hasRnD: true,
    hr: { roles: ["Производство", "R&D", "QA/QC"], careerSite: "https://pharmasyntez.com/", note: "Сильные позиции в социально значимых препаратах (ТБ, ВИЧ)." },
    website: "https://pharmasyntez.com/",
    logoColor: "#0369a1",
    note: ""
  },
  {
    name: "Обновление (ПФК)",
    marketRank: 7,
    fullName: "АО «Производственная фармацевтическая компания Обновление» (Renewal)",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Новосибирская область"],
    factories: [
      { city: "Новосибирск", lat: 55.0084, lng: 82.9357, products: "Дженерики, готовые формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: 25.6,
    revenueYear: 2025,
    yearEnteredRussia: 1997,
    segments: ["Дженерики", "OTC"],
    therapeuticAreas: ["Широкий профиль"],
    keyProducts: ["Renewal — массовые дженерики"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "https://renewal.ru/", note: "" },
    website: "https://renewal.ru/",
    logoColor: "#65a30d",
    note: ""
  },
  {
    name: "Р-Фарм",
    marketRank: 8,
    fullName: "АО «Р-Фарм»",
    country: "РФ",
    status: "Российская · системообразующая",
    hasProductionInRussia: true,
    regions: ["Ярославская область", "Москва", "Костромская область"],
    factories: [
      { city: "Ярославль", lat: 57.6261, lng: 39.8845, products: "Готовые формы, терапевтические белки, АФИ", gmp: "Да" },
      { city: "Москва (Технополис)", lat: 55.7000, lng: 37.6800, products: "Вакцины («Спутник Технополис»)", gmp: "Да" },
      { city: "Кострома (Ортат)", lat: 57.7679, lng: 40.9269, products: "Твёрдые и стерильные формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: 21.0,
    revenueYear: 2025,
    yearEnteredRussia: 2001,
    segments: ["Рецептурные", "Биотех", "Вакцины", "Оригинальные"],
    therapeuticAreas: ["Онкология", "Инфекционные", "Ревматология", "Госпитальный сегмент"],
    keyProducts: ["Арланса (нарлапревир)", "Артлегиа", "Коронавир"],
    hasRnD: true,
    hr: { roles: ["Производство", "R&D", "Клинические исследования", "Медицина"], careerSite: "https://career.rpharm.com/vacancies", note: "Филиалы в Германии, США, Японии. Системообразующее предприятие." },
    website: "https://rpharm.ru/",
    logoColor: "#1d4ed8",
    note: "Основана Алексеем Репиком в 2001 г. Заводы Pfizer (Германия) и Teva (Ярославль) в составе группы."
  },
  {
    name: "Велфарм Групп",
    marketRank: 9,
    fullName: "ООО «Велфарм Групп»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Курганская область", "Москва"],
    factories: [
      { city: "Курган", lat: 55.4500, lng: 65.3333, products: "Готовые лекарственные формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: 20.1,
    revenueYear: 2025,
    yearEnteredRussia: 2015,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Широкий профиль"],
    keyProducts: ["Портфель дженериков"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "", note: "" },
    website: "https://welfarm.ru/",
    logoColor: "#16a34a",
    note: ""
  },
  {
    name: "ПромоМед",
    marketRank: 10,
    fullName: "ПАО «ПРОМОМЕД» (завод «Биохимик», Саранск)",
    country: "РФ",
    status: "Российская · публичная (MOEX)",
    hasProductionInRussia: true,
    regions: ["Республика Мордовия"],
    factories: [
      { city: "Саранск (Биохимик)", lat: 54.1838, lng: 45.1749, products: "АФИ, антибиотики, биотех, готовые формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: 21.4,
    revenueYear: 2024,
    yearEnteredRussia: 2005,
    segments: ["Оригинальные", "Биотех", "Дженерики", "Рецептурные"],
    therapeuticAreas: ["Эндокринология (ожирение/диабет)", "Онкология", "Инфекционные"],
    keyProducts: ["Велгия (семаглутид)", "Тирзетта (тирзепатид)", "Арепливир"],
    hasRnD: true,
    hr: { roles: ["R&D", "Биопроизводство", "Клинические исследования", "QA/QC"], careerSite: "https://promomed.ru/", note: "Лидер РФ по аналогам инкретиновых препаратов (ожирение, диабет). IPO в 2024 г." },
    website: "https://promomed.ru/",
    logoColor: "#9333ea",
    note: "Полный цикл по семаглутиду и тирзепатиду. Сильный пайплайн в метаболике и онкологии."
  },
  {
    name: "Герофарм",
    fullName: "ООО «Герофарм»",
    country: "РФ",
    status: "Российская · полный цикл (инсулины)",
    hasProductionInRussia: true,
    regions: ["Санкт-Петербург", "Московская область"],
    factories: [
      { city: "Оболенск (МО)", lat: 54.9333, lng: 37.3667, products: "Инсулины полного цикла", gmp: "Да" },
      { city: "Пушкин (СПб)", lat: 59.7142, lng: 30.4163, products: "Готовые формы, субстанции", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: 35.2,
    revenueYear: 2025,
    yearEnteredRussia: 2001,
    segments: ["Биотех", "Оригинальные"],
    therapeuticAreas: ["Эндокринология (диабет)", "Неврология"],
    keyProducts: ["Современные инсулины (от субстанции до готовой формы)", "Семаглутид (разработка)"],
    hasRnD: true,
    hr: { roles: ["Биопроизводство", "R&D", "QA/QC"], careerSite: "https://geropharm.ru/", note: "Крупнейший российский производитель современных инсулинов." },
    website: "https://geropharm.ru/",
    logoColor: "#0d9488",
    note: "Производство инсулинов полного цикла."
  },
  {
    name: "Валента Фарм",
    fullName: "АО «Валента Фарм»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Московская область"],
    factories: [
      { city: "Щёлково (МО)", lat: 55.9203, lng: 38.0094, products: "Готовые лекарственные формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: 31.5,
    revenueYear: 2025,
    yearEnteredRussia: 1997,
    segments: ["Рецептурные", "OTC", "Оригинальные"],
    therapeuticAreas: ["Неврология", "Психиатрия", "Иммунология", "Гастроэнтерология"],
    keyProducts: ["Феназепам", "Граммидин", "Ингавирин"],
    hasRnD: true,
    hr: { roles: ["Производство", "R&D", "Медпредставители"], careerSite: "https://valentapharm.com/", note: "" },
    website: "https://valentapharm.com/",
    logoColor: "#ea580c",
    note: ""
  },
  {
    name: "Вертекс",
    fullName: "АО «Вертекс»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Санкт-Петербург"],
    factories: [
      { city: "Санкт-Петербург (ОЭЗ Новоорловская)", lat: 60.0500, lng: 30.2500, products: "Твёрдые и мягкие формы, косметика", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: 29.5,
    revenueYear: 2025,
    yearEnteredRussia: 2001,
    segments: ["Дженерики", "OTC", "Рецептурные"],
    therapeuticAreas: ["Кардиология", "Дерматология", "Широкий профиль"],
    keyProducts: ["Портфель дженериков и дермокосметики"],
    hasRnD: true,
    hr: { roles: ["Производство", "QC/QA", "Продажи"], careerSite: "https://vertex.spb.ru/", note: "" },
    website: "https://vertex.spb.ru/",
    logoColor: "#4f46e5",
    note: ""
  },
  {
    name: "Гротекс (Solopharm)",
    fullName: "ООО «Гротекс» (бренд Solopharm)",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Санкт-Петербург"],
    factories: [
      { city: "Санкт-Петербург", lat: 59.8333, lng: 30.3333, products: "Стерильные жидкие формы, офтальмология", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: 26.9,
    revenueYear: 2025,
    yearEnteredRussia: 2010,
    segments: ["Дженерики", "OTC"],
    therapeuticAreas: ["Офтальмология", "ЛОР", "Широкий профиль"],
    keyProducts: ["Solopharm — капли и стерильные растворы"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "https://solopharm.com/", note: "" },
    website: "https://solopharm.com/",
    logoColor: "#0284c7",
    note: ""
  },
  {
    name: "Нацимбио",
    fullName: "АО «Нацимбио» (ГК «Ростех»)",
    country: "РФ",
    status: "Российская · госкорпорация",
    hasProductionInRussia: true,
    regions: ["Москва", "Пермский край", "Уфа", "Томская область"],
    factories: [
      { city: "Пермь (НПО «Микроген»)", lat: 58.0105, lng: 56.2502, products: "Вакцины, иммунобиология", gmp: "Да" },
      { city: "Уфа", lat: 54.7388, lng: 55.9721, products: "Вакцины, препараты крови", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: 23.9,
    revenueYear: 2025,
    yearEnteredRussia: 2013,
    segments: ["Вакцины", "Биотех"],
    therapeuticAreas: ["Иммунопрофилактика", "Инфекционные", "Гематология"],
    keyProducts: ["Вакцины НКПП", "Препараты крови"],
    hasRnD: true,
    hr: { roles: ["Биопроизводство", "QC", "R&D"], careerSite: "https://natimbio.ru/", note: "Национальный оператор иммунобиологии. Включает «Микроген»." },
    website: "https://natimbio.ru/",
    logoColor: "#be123c",
    note: ""
  },
  {
    name: "Канонфарма",
    fullName: "ООО «Канонфарма продакшн»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Московская область"],
    factories: [
      { city: "Щёлково (МО)", lat: 55.9203, lng: 38.0094, products: "Дженерики, онкология", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: 17.8,
    revenueYear: 2025,
    yearEnteredRussia: 2009,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Онкология", "Кардиология", "Широкий профиль"],
    keyProducts: ["Портфель дженериков, онкопрепараты"],
    hasRnD: true,
    hr: { roles: ["Производство", "R&D", "QC"], careerSite: "https://canonpharma.ru/", note: "" },
    website: "https://canonpharma.ru/",
    logoColor: "#7e22ce",
    note: ""
  },
  {
    name: "Северная звезда",
    fullName: "АО «Северная звезда»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Санкт-Петербург", "Ленинградская область"],
    factories: [
      { city: "Кузьмоловский (ЛО)", lat: 60.1167, lng: 30.5000, products: "Дженерики, онкология", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: 17.9,
    revenueYear: 2025,
    yearEnteredRussia: 2008,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Онкология", "Кардиология", "Широкий профиль"],
    keyProducts: ["Дженерики, онкопрепараты"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "", note: "" },
    website: "https://nstar-spb.ru/",
    logoColor: "#0e7490",
    note: ""
  },
  {
    name: "Активный Компонент",
    fullName: "АО «Активный Компонент»",
    country: "РФ",
    status: "Российская · производитель АФИ",
    hasProductionInRussia: true,
    regions: ["Санкт-Петербург", "Ленинградская область"],
    factories: [
      { city: "Санкт-Петербург", lat: 59.9343, lng: 30.3351, products: "Активные фармацевтические субстанции (АФИ)", gmp: "Да" },
      { city: "Пушкин (ОЭЗ)", lat: 59.7142, lng: 30.4163, products: "Синтез субстанций", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2009,
    segments: ["Дженерики"],
    therapeuticAreas: ["Производство субстанций (широкий профиль)"],
    keyProducts: ["Десятки АФИ для российских производителей"],
    hasRnD: true,
    hr: { roles: ["Химики-синтетики", "R&D", "QC/QA", "Производство"], careerSite: "https://aktivcomponent.com/", note: "Один из крупнейших независимых производителей фармсубстанций в РФ." },
    website: "https://aktivcomponent.com/",
    logoColor: "#0891b2",
    note: "Импортозамещение по активным фармацевтическим субстанциям."
  },
  {
    name: "Полисан",
    fullName: "ООО «НТФФ «ПОЛИСАН»",
    country: "РФ",
    status: "Российская · полный цикл",
    hasProductionInRussia: true,
    regions: ["Санкт-Петербург"],
    factories: [
      { city: "Санкт-Петербург", lat: 59.9343, lng: 30.3351, products: "Оригинальные препараты, инфузионные растворы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1992,
    segments: ["Оригинальные", "Рецептурные"],
    therapeuticAreas: ["Неврология", "Гепатология", "Инфекционные"],
    keyProducts: ["Цитофлавин", "Циклоферон", "Реамберин", "Ремаксол"],
    hasRnD: true,
    hr: { roles: ["Производство", "R&D", "QA/QC", "Медицина"], careerSite: "https://polysan.ru/", note: "Контрактное производство для зарубежных партнёров (Bayer, STADA)." },
    website: "https://polysan.ru/",
    logoColor: "#1d4ed8",
    note: ""
  },
  {
    name: "Эвалар",
    fullName: "ЗАО «Эвалар»",
    country: "РФ",
    status: "Российская · лидер БАД/OTC",
    hasProductionInRussia: true,
    regions: ["Алтайский край"],
    factories: [
      { city: "Бийск", lat: 52.5394, lng: 85.2072, products: "БАД, OTC, фитопрепараты", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1991,
    segments: ["OTC"],
    therapeuticAreas: ["Витамины и БАД", "Фитотерапия", "Широкий профиль"],
    keyProducts: ["Антистрессовые, витаминные и фитолинейки Эвалар"],
    hasRnD: true,
    hr: { roles: ["Производство", "R&D", "Маркетинг", "Продажи"], careerSite: "https://evalar.ru/", note: "Крупнейший российский производитель БАД и натуральных OTC." },
    website: "https://evalar.ru/",
    logoColor: "#16a34a",
    note: ""
  },
  {
    name: "Генериум",
    fullName: "АО «ГЕНЕРИУМ»",
    country: "РФ",
    status: "Российская · биотех полного цикла",
    hasProductionInRussia: true,
    regions: ["Владимирская область"],
    factories: [
      { city: "Вольгинский (Владимирская обл.)", lat: 55.9610, lng: 39.2510, products: "Биотех, факторы свёртывания, диагностика", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2009,
    segments: ["Биотех", "Оригинальные"],
    therapeuticAreas: ["Гематология", "Орфанные заболевания", "Фтизиатрия (диагностика)"],
    keyProducts: ["Факторы свёртывания крови", "Диаскинтест", "Орфанные биопрепараты"],
    hasRnD: true,
    hr: { roles: ["Учёные/R&D", "Биопроизводство", "Клинические исследования"], careerSite: "https://generium.ru/", note: "Один из ведущих биотех-центров полного цикла в РФ." },
    website: "https://generium.ru/",
    logoColor: "#0d9488",
    note: ""
  },
  {
    name: "Петровакс Фарм",
    fullName: "ООО «НПО Петровакс Фарм»",
    country: "РФ",
    status: "Российская · вакцины и иммунобиология",
    hasProductionInRussia: true,
    regions: ["Московская область"],
    factories: [
      { city: "Покров (Московская обл.)", lat: 55.3600, lng: 37.5200, products: "Вакцины, иммуномодуляторы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1996,
    segments: ["Вакцины", "Биотех", "Оригинальные"],
    therapeuticAreas: ["Иммунопрофилактика", "Иммунология", "Инфекционные"],
    keyProducts: ["Полиоксидоний", "Гриппол плюс", "Превенар 13 (локализация с Pfizer)"],
    hasRnD: true,
    hr: { roles: ["Биопроизводство", "R&D", "QA/QC", "Медицина"], careerSite: "https://petrovax.ru/", note: "Локализация пневмококковой вакцины Pfizer; собственные иммунопрепараты." },
    website: "https://petrovax.ru/",
    logoColor: "#be123c",
    note: ""
  },
  {
    name: "Нанолек",
    fullName: "ООО «Нанолек»",
    country: "РФ",
    status: "Российская · вакцины и биотех",
    hasProductionInRussia: true,
    regions: ["Кировская область"],
    factories: [
      { city: "Лёвинцы (Кировская обл.)", lat: 58.7800, lng: 49.4000, products: "Вакцины, биопрепараты полного цикла", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2011,
    segments: ["Вакцины", "Биотех"],
    therapeuticAreas: ["Иммунопрофилактика (детская)", "Инфекционные"],
    keyProducts: ["Вакцина против ВПЧ (Цегардекс)", "Комбинированные детские вакцины"],
    hasRnD: true,
    hr: { roles: ["Биопроизводство", "R&D", "QA/QC"], careerSite: "https://nanolek.ru/", note: "Локализация и собственная разработка вакцин, в т.ч. против ВПЧ." },
    website: "https://nanolek.ru/",
    logoColor: "#0ea5e9",
    note: ""
  },
  {
    name: "Натива",
    fullName: "ООО «Натива»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Московская область"],
    factories: [
      { city: "Красногорск / Сабурово (МО)", lat: 55.8311, lng: 37.3300, products: "Дженерики, онкология, ингаляционные формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2008,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Онкология", "Пульмонология", "Гематология"],
    keyProducts: ["Воспроизведённые онкопрепараты", "Ингаляционные ЛП"],
    hasRnD: true,
    hr: { roles: ["Производство", "R&D", "QC/QA"], careerSite: "https://nativa.pro/", note: "" },
    website: "https://nativa.pro/",
    logoColor: "#7c3aed",
    note: ""
  },
  {
    name: "Аксельфарм",
    fullName: "ООО «Аксельфарм»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Москва"],
    factories: [
      { city: "Москва", lat: 55.7558, lng: 37.6173, products: "Онкология, биосимиляры, готовые формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2018,
    segments: ["Дженерики", "Биотех", "Рецептурные"],
    therapeuticAreas: ["Онкология", "Гематология", "Иммунология"],
    keyProducts: ["Воспроизведённые онко- и биопрепараты"],
    hasRnD: true,
    hr: { roles: ["Производство", "R&D", "QC/QA"], careerSite: "", note: "" },
    website: "https://axelpharm.com/",
    logoColor: "#9333ea",
    note: ""
  },
  {
    name: "Фарм-Синтез",
    fullName: "ЗАО «Фарм-Синтез»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Москва"],
    factories: [
      { city: "Москва", lat: 55.7558, lng: 37.6173, products: "Пептидные и онкопрепараты, готовые формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1996,
    segments: ["Оригинальные", "Дженерики", "Рецептурные"],
    therapeuticAreas: ["Онкология", "Эндокринология", "Неврология"],
    keyProducts: ["Бусерелин", "Пептидные препараты"],
    hasRnD: true,
    hr: { roles: ["Производство", "R&D", "QC/QA"], careerSite: "", note: "" },
    website: "https://pharm-sintez.ru/",
    logoColor: "#0369a1",
    note: ""
  },
  {
    name: "Медсинтез",
    fullName: "ООО «Завод Медсинтез» (Уральский фармкластер)",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Свердловская область"],
    factories: [
      { city: "Новоуральск", lat: 57.2470, lng: 60.0935, products: "Инсулины, инфузионные растворы, готовые формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2003,
    segments: ["Биотех", "Дженерики", "Рецептурные"],
    therapeuticAreas: ["Эндокринология (диабет)", "Инфузионная терапия"],
    keyProducts: ["Росинсулин", "Инфузионные растворы"],
    hasRnD: true,
    hr: { roles: ["Производство", "R&D", "QC/QA"], careerSite: "https://medsintez.com/", note: "Ядро Уральского фармацевтического кластера." },
    website: "https://medsintez.com/",
    logoColor: "#0d9488",
    note: ""
  },
  {
    name: "Авексима",
    fullName: "АО «Авексима»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Иркутская область", "Москва"],
    factories: [
      { city: "Усолье-Сибирское (Авексима Сибирь)", lat: 52.7500, lng: 103.6400, products: "Готовые формы, OTC, таблетки", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2013,
    segments: ["OTC", "Дженерики", "Рецептурные"],
    therapeuticAreas: ["Гастроэнтерология", "Простуда и грипп", "Широкий профиль"],
    keyProducts: ["Портфель OTC и рецептурных дженериков"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA", "Маркетинг"], careerSite: "https://aveksima.ru/", note: "" },
    website: "https://aveksima.ru/",
    logoColor: "#ea580c",
    note: ""
  },
  {
    name: "ХимРар",
    fullName: "ГК «ХимРар» (Центр высоких технологий)",
    country: "РФ",
    status: "Российская · R&D и инновации",
    hasProductionInRussia: true,
    regions: ["Московская область"],
    factories: [
      { city: "Химки (МО)", lat: 55.8970, lng: 37.4297, products: "Малотоннажный синтез, R&D, опытное производство", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1990,
    segments: ["Оригинальные", "Биотех"],
    therapeuticAreas: ["Инфекционные", "Онкология", "Неврология"],
    keyProducts: ["Авифавир (фавипиравир)", "Скайфейзер", "Разработка новых молекул"],
    hasRnD: true,
    hr: { roles: ["Учёные/R&D", "Медицинская химия", "Клинические исследования"], careerSite: "https://chemrar.ru/", note: "Один из ведущих частных R&D-центров по разработке лекарств в РФ." },
    website: "https://chemrar.ru/",
    logoColor: "#6366f1",
    note: ""
  },
  {
    name: "Materia Medica",
    fullName: "ООО «НПФ «Материа Медика Холдинг»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Москва", "Московская область"],
    factories: [
      { city: "Москва", lat: 55.7558, lng: 37.6173, products: "Готовые лекарственные формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1993,
    segments: ["OTC", "Рецептурные", "Оригинальные"],
    therapeuticAreas: ["Простуда и грипп", "Неврология", "Урология"],
    keyProducts: ["Анаферон", "Тенотен", "Эргоферон", "Импаза"],
    hasRnD: true,
    hr: { roles: ["R&D", "Производство", "Маркетинг"], careerSite: "https://materiamedica.ru/", note: "" },
    website: "https://materiamedica.ru/",
    logoColor: "#0891b2",
    note: ""
  },
  {
    name: "Фармимэкс",
    fullName: "АО «Фармимэкс»",
    country: "РФ",
    status: "Российская · дистрибуция и производство",
    hasProductionInRussia: true,
    regions: ["Москва", "Владимирская область"],
    factories: [
      { city: "Владимирская область", lat: 56.1290, lng: 40.4070, products: "Биотех, готовые формы (через дочерние активы)", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1991,
    segments: ["Биотех", "Рецептурные", "Дженерики"],
    therapeuticAreas: ["Гематология", "Орфанные заболевания", "Госпитальный сегмент"],
    keyProducts: ["Дистрибуция + производство биопрепаратов"],
    hasRnD: false,
    hr: { roles: ["Логистика", "Производство", "Регистрация"], careerSite: "https://pharmimex.ru/", note: "Один из старейших фармдистрибьюторов РФ с производственными активами." },
    website: "https://pharmimex.ru/",
    logoColor: "#1d4ed8",
    note: ""
  },
  {
    name: "Татхимфармпрепараты",
    fullName: "АО «Татхимфармпрепараты»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Республика Татарстан"],
    factories: [
      { city: "Казань", lat: 55.7963, lng: 49.1088, products: "Готовые формы, шовные материалы, медизделия", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1932,
    segments: ["Дженерики", "OTC", "Рецептурные"],
    therapeuticAreas: ["Широкий профиль", "Хирургия (шовные материалы)"],
    keyProducts: ["Дженерики, таблетки, мази; шовные материалы"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "https://tatpharm.ru/", note: "Одно из старейших предприятий отрасли (с 1932 г.)." },
    website: "https://tatpharm.ru/",
    logoColor: "#b45309",
    note: ""
  },
  {
    name: "Дальхимфарм",
    fullName: "ОАО «Дальхимфарм»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Хабаровский край"],
    factories: [
      { city: "Хабаровск", lat: 48.4827, lng: 135.0838, products: "Готовые формы, ампулы, таблетки, мази", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1939,
    segments: ["Дженерики", "OTC"],
    therapeuticAreas: ["Широкий профиль"],
    keyProducts: ["Массовые дженерики, ампульные препараты"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "https://dalhimfarm.ru/", note: "Крупнейший производитель ЛС на Дальнем Востоке." },
    website: "https://dalhimfarm.ru/",
    logoColor: "#0e7490",
    note: ""
  },
  {
    name: "Усолье-Сибирский ХФЗ",
    fullName: "ОАО «Усолье-Сибирский химико-фармацевтический завод»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Иркутская область"],
    factories: [
      { city: "Усолье-Сибирское", lat: 52.7500, lng: 103.6400, products: "Субстанции, готовые формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1939,
    segments: ["Дженерики", "OTC"],
    therapeuticAreas: ["Широкий профиль"],
    keyProducts: ["Субстанции и готовые формы"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "", note: "" },
    website: "https://ushfz.ru/",
    logoColor: "#65a30d",
    note: ""
  },
  {
    name: "Московский эндокринный завод",
    fullName: "ФГУП «Московский эндокринный завод»",
    country: "РФ",
    status: "Российская · государственная",
    hasProductionInRussia: true,
    regions: ["Москва", "Брянская область"],
    factories: [
      { city: "Москва", lat: 55.7558, lng: 37.6173, products: "Наркотические анальгетики, гормоны, офтальмология", gmp: "Да" },
      { city: "Брянск (площадка)", lat: 53.2521, lng: 34.3717, products: "Производство ЛП", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1943,
    segments: ["Рецептурные", "Оригинальные"],
    therapeuticAreas: ["Анестезиология и обезболивание", "Эндокринология", "Офтальмология"],
    keyProducts: ["Опиоидные анальгетики", "Гормональные препараты"],
    hasRnD: true,
    hr: { roles: ["Производство", "QC/QA", "Безопасность"], careerSite: "https://endopharm.ru/", note: "Ключевой государственный производитель наркотических анальгетиков." },
    website: "https://endopharm.ru/",
    logoColor: "#475569",
    note: ""
  },
  {
    name: "Самсон-Мед",
    fullName: "ООО «Самсон-Мед»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Санкт-Петербург"],
    factories: [
      { city: "Санкт-Петербург", lat: 59.9343, lng: 30.3351, products: "Ферментные, гормональные, органопрепараты", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2002,
    segments: ["Рецептурные", "Дженерики"],
    therapeuticAreas: ["Гастроэнтерология", "Эндокринология", "Урология"],
    keyProducts: ["Ферментные и органотропные препараты"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "", note: "" },
    website: "https://samson-med.ru/",
    logoColor: "#0284c7",
    note: ""
  },
  {
    name: "Тульская фармфабрика",
    fullName: "АО «Тульская фармацевтическая фабрика»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Тульская область"],
    factories: [
      { city: "Тула", lat: 54.1930, lng: 37.6173, products: "Настойки, растворы, OTC", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1944,
    segments: ["OTC", "Дженерики"],
    therapeuticAreas: ["Широкий профиль", "Фитотерапия"],
    keyProducts: ["Спиртовые настойки, антисептики, растворы"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "", note: "" },
    website: "https://tulpharm.ru/",
    logoColor: "#b45309",
    note: ""
  },
  {
    name: "Эколаб",
    fullName: "ЗАО «ЭКОлаб»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Московская область"],
    factories: [
      { city: "Электрогорск (МО)", lat: 55.8830, lng: 38.7910, products: "Диагностикумы, дезсредства, ЛП", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1991,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Инфекционные (диагностика)", "Широкий профиль"],
    keyProducts: ["Тест-системы, дезинфицирующие средства, ЛП"],
    hasRnD: true,
    hr: { roles: ["Производство", "R&D", "QC/QA"], careerSite: "https://ecolab.ru/", note: "" },
    website: "https://ecolab.ru/",
    logoColor: "#059669",
    note: ""
  },
  {
    name: "Фирн М",
    fullName: "ЗАО «ФИРН М»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Москва"],
    factories: [
      { city: "Москва", lat: 55.7558, lng: 37.6173, products: "Пептидные препараты, готовые формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1991,
    segments: ["Оригинальные", "Рецептурные"],
    therapeuticAreas: ["Неврология", "Офтальмология"],
    keyProducts: ["Семакс", "Селанк"],
    hasRnD: true,
    hr: { roles: ["Производство", "R&D", "QC/QA"], careerSite: "", note: "Оригинальные пептидные ноотропы (совместная разработка с РАН)." },
    website: "https://firnm.ru/",
    logoColor: "#6366f1",
    note: ""
  },
  {
    name: "Эском",
    fullName: "ОАО «НПК «ЭСКОМ»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Ставропольский край"],
    factories: [
      { city: "Ставрополь", lat: 45.0445, lng: 41.9690, products: "Инфузионные растворы, ампулы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1997,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Инфузионная терапия", "Реаниматология"],
    keyProducts: ["Инфузионные растворы в полимерной упаковке"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "", note: "" },
    website: "https://escom-ru.ru/",
    logoColor: "#0e7490",
    note: ""
  },
  {
    name: "Авва Рус",
    fullName: "АО «АВВА РУС»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Нижегородская область", "Кировская область"],
    factories: [
      { city: "Балахна (Нижегородская обл.)", lat: 56.4900, lng: 43.6000, products: "Готовые лекарственные формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2002,
    segments: ["Дженерики", "OTC", "Рецептурные"],
    therapeuticAreas: ["Широкий профиль", "Неврология"],
    keyProducts: ["Портфель дженериков и OTC"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "", note: "" },
    website: "https://avva-rus.ru/",
    logoColor: "#7c3aed",
    note: ""
  },
  {
    name: "Фармпроект",
    fullName: "АО «Фармпроект»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Санкт-Петербург"],
    factories: [
      { city: "Санкт-Петербург", lat: 59.9343, lng: 30.3351, products: "Готовые формы, ЛОР, неврология", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1999,
    segments: ["Дженерики", "OTC", "Рецептурные"],
    therapeuticAreas: ["ЛОР", "Неврология", "Широкий профиль"],
    keyProducts: ["Портфель рецептурных и OTC дженериков"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "", note: "" },
    website: "https://pharmproject.ru/",
    logoColor: "#0284c7",
    note: ""
  },
  {
    name: "Тверская фармфабрика",
    fullName: "ОАО «Тверская фармацевтическая фабрика»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Тверская область"],
    factories: [
      { city: "Тверь", lat: 56.8587, lng: 35.9176, products: "Настойки, растворы, OTC", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1944,
    segments: ["OTC", "Дженерики"],
    therapeuticAreas: ["Широкий профиль", "Фитотерапия"],
    keyProducts: ["Настойки, антисептики, OTC"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "", note: "" },
    website: "https://tverfarm.ru/",
    logoColor: "#b45309",
    note: ""
  },
  {
    name: "Московская фармфабрика",
    fullName: "АО «Московская фармацевтическая фабрика»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Москва"],
    factories: [
      { city: "Москва", lat: 55.7558, lng: 37.6173, products: "Настойки, мази, растворы, OTC", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1939,
    segments: ["OTC", "Дженерики"],
    therapeuticAreas: ["Дерматология", "Широкий профиль"],
    keyProducts: ["Мази, настойки, растворы"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "", note: "" },
    website: "https://mosfarma.ru/",
    logoColor: "#dc2626",
    note: ""
  },
  {
    name: "Ярославская фармфабрика",
    fullName: "ЗАО «Ярославская фармацевтическая фабрика»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Ярославская область"],
    factories: [
      { city: "Ярославль", lat: 57.6261, lng: 39.8845, products: "Настойки, сиропы, OTC", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1939,
    segments: ["OTC", "Дженерики"],
    therapeuticAreas: ["Широкий профиль", "Фитотерапия"],
    keyProducts: ["Настойки, сиропы, растворы"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "", note: "" },
    website: "https://yarpharma.ru/",
    logoColor: "#0d9488",
    note: ""
  },
  {
    name: "Кировская фармфабрика",
    fullName: "АО «Кировская фармацевтическая фабрика»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Кировская область"],
    factories: [
      { city: "Киров", lat: 58.6035, lng: 49.6679, products: "Настойки, растворы, OTC", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1939,
    segments: ["OTC", "Дженерики"],
    therapeuticAreas: ["Широкий профиль"],
    keyProducts: ["Настойки, антисептики, растворы"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "", note: "" },
    website: "https://kirovpharm.ru/",
    logoColor: "#65a30d",
    note: ""
  },
  {
    name: "Ивановская фармфабрика",
    fullName: "АО «Ивановская фармацевтическая фабрика»",
    country: "РФ",
    status: "Российская",
    hasProductionInRussia: true,
    regions: ["Ивановская область"],
    factories: [
      { city: "Иваново", lat: 57.0004, lng: 40.9739, products: "Настойки, растворы, OTC", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1944,
    segments: ["OTC", "Дженерики"],
    therapeuticAreas: ["Широкий профиль", "Фитотерапия"],
    keyProducts: ["Настойки, растворы, OTC"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "", note: "" },
    website: "https://ivanovofarm.ru/",
    logoColor: "#b45309",
    note: ""
  },
  {
    name: "НИЦЭМ им. Гамалеи",
    fullName: "ФГБУ «НИЦЭМ им. Н.Ф. Гамалеи» Минздрава России",
    country: "РФ",
    status: "Российская · государственный НИЦ",
    hasProductionInRussia: true,
    regions: ["Москва"],
    factories: [
      { city: "Москва", lat: 55.7558, lng: 37.6173, products: "Вакцины (разработка), опытное производство", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1891,
    segments: ["Вакцины", "Биотех", "Оригинальные"],
    therapeuticAreas: ["Иммунопрофилактика", "Инфекционные", "Эпидемиология"],
    keyProducts: ["Спутник V (Гам-КОВИД-Вак)", "Спутник Лайт"],
    hasRnD: true,
    hr: { roles: ["Учёные/R&D", "Вирусология", "Клинические исследования"], careerSite: "https://gamaleya.org/", note: "Разработчик первой зарегистрированной вакцины от COVID-19. Производство — через партнёров." },
    website: "https://gamaleya.org/",
    logoColor: "#be123c",
    note: ""
  },
  {
    name: "ГНЦ ВБ «Вектор»",
    fullName: "ФБУН ГНЦ ВБ «Вектор» Роспотребнадзора",
    country: "РФ",
    status: "Российская · государственный НИЦ",
    hasProductionInRussia: true,
    regions: ["Новосибирская область"],
    factories: [
      { city: "Кольцово (Новосибирская обл.)", lat: 54.9367, lng: 83.1800, products: "Вакцины, диагностикумы, опытное производство", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1974,
    segments: ["Вакцины", "Биотех"],
    therapeuticAreas: ["Иммунопрофилактика", "Вирусология", "Инфекционные"],
    keyProducts: ["ЭпиВакКорона", "Тест-системы и диагностикумы"],
    hasRnD: true,
    hr: { roles: ["Учёные/R&D", "Вирусология", "QC"], careerSite: "https://www.vector.nsc.ru/", note: "Один из крупнейших вирусологических центров России." },
    website: "https://www.vector.nsc.ru/",
    logoColor: "#0369a1",
    note: ""
  },
  {
    name: "ФНЦИРИП им. Чумакова",
    fullName: "ФГАНУ «ФНЦИРИП им. М.П. Чумакова РАН»",
    country: "РФ",
    status: "Российская · государственный НИЦ",
    hasProductionInRussia: true,
    regions: ["Москва"],
    factories: [
      { city: "Москва (пос. Института полиомиелита)", lat: 55.5500, lng: 37.4000, products: "Вакцины (полиомиелит, КЭ, COVID-19)", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1955,
    segments: ["Вакцины", "Биотех"],
    therapeuticAreas: ["Иммунопрофилактика", "Инфекционные"],
    keyProducts: ["КовиВак", "Вакцины против полиомиелита", "Вакцина против клещевого энцефалита"],
    hasRnD: true,
    hr: { roles: ["Учёные/R&D", "Вирусология", "Биопроизводство"], careerSite: "https://www.chumakovs.su/", note: "Полный цикл от разработки до промышленного выпуска вакцин." },
    website: "https://www.chumakovs.su/",
    logoColor: "#9333ea",
    note: ""
  },
  /* ===================== СОВМЕСТНЫЕ ПРЕДПРИЯТИЯ / ЛОКАЛИЗАЦИЯ ===================== */
  {
    name: "Верофарм",
    fullName: "АО «Верофарм» (группа Abbott)",
    country: "СП",
    status: "Российская в группе Abbott",
    hasProductionInRussia: true,
    regions: ["Воронежская область", "Белгородская область", "Владимирская область"],
    factories: [
      { city: "Воронеж", lat: 51.6720, lng: 39.1843, products: "Готовые формы, пластыри", gmp: "Да" },
      { city: "Белгород", lat: 50.5977, lng: 36.5858, products: "Таблетки, капсулы", gmp: "Да" },
      { city: "Покров", lat: 55.9181, lng: 39.1736, products: "Онкология, готовые формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1997,
    segments: ["Дженерики", "OTC", "Рецептурные"],
    therapeuticAreas: ["Онкология", "Гинекология", "Широкий профиль"],
    keyProducts: ["Портфель Abbott в РФ", "Пластыри"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA", "Продажи"], careerSite: "https://www.veropharm.ru/", note: "Основана в России, входит в международную группу Abbott." },
    website: "https://www.veropharm.ru/",
    logoColor: "#0f766e",
    note: ""
  },
  {
    name: "Нижфарм (STADA)",
    fullName: "АО «Нижфарм» (группа STADA)",
    country: "СП",
    status: "Российская в группе STADA",
    hasProductionInRussia: true,
    regions: ["Нижегородская область", "Москва (Сотекс)"],
    factories: [
      { city: "Нижний Новгород", lat: 56.3269, lng: 44.0059, products: "Мягкие, твёрдые формы", gmp: "Да" },
      { city: "Сергиев Посад (Сотекс)", lat: 56.3000, lng: 38.1333, products: "Инъекционные формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1919,
    segments: ["Дженерики", "OTC", "Рецептурные"],
    therapeuticAreas: ["Дерматология", "Кардиология", "Широкий профиль"],
    keyProducts: ["Портфель STADA в РФ"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA", "Продажи"], careerSite: "https://nizhpharm.ru/", note: "В 2025 г. сместила Bayer с 1 места розничного рейтинга RNC Pharma." },
    website: "https://nizhpharm.ru/",
    logoColor: "#1e40af",
    note: "Лидер розничного рейтинга RNC Pharma по итогам 2025 г."
  },
  {
    name: "Акрихин",
    fullName: "АО «Акрихин» (группа Polpharma)",
    country: "СП",
    status: "Российская в группе Polpharma",
    hasProductionInRussia: true,
    regions: ["Московская область"],
    factories: [
      { city: "Старая Купавна (МО)", lat: 55.8061, lng: 38.1731, products: "Готовые формы, широкий профиль", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1936,
    segments: ["Дженерики", "OTC", "Рецептурные"],
    therapeuticAreas: ["Дерматология", "Эндокринология", "Широкий профиль"],
    keyProducts: ["Портфель дженериков"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA", "Продажи"], careerSite: "https://akrikhin.ru/", note: "Один из старейших фармзаводов России (с 1936 г.)." },
    website: "https://akrikhin.ru/",
    logoColor: "#b91c1c",
    note: ""
  },
  {
    name: "Биосинтез (Sun Pharma)",
    fullName: "ПАО «Биосинтез» (группа Sun Pharma)",
    country: "СП",
    status: "Российская в группе Sun Pharma (Индия)",
    hasProductionInRussia: true,
    regions: ["Пензенская область"],
    factories: [
      { city: "Пенза", lat: 53.2007, lng: 45.0046, products: "Антибиотики, инфузии, готовые формы, субстанции", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1955,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Антибиотики", "Инфузионная терапия", "Широкий профиль"],
    keyProducts: ["Антибиотики, инфузионные растворы"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "https://biosintez.com/", note: "Контролируется индийской Sun Pharma." },
    website: "https://biosintez.com/",
    logoColor: "#ca8a04",
    note: ""
  },
  {
    name: "ЗиО-Здоровье (STADA)",
    fullName: "АО «ЗиО-Здоровье» (группа STADA)",
    country: "СП",
    status: "Российская в группе STADA",
    hasProductionInRussia: true,
    regions: ["Московская область"],
    factories: [
      { city: "Подольск (МО)", lat: 55.4312, lng: 37.5457, products: "Твёрдые лекарственные формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: "н/д",
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2005,
    segments: ["Дженерики", "OTC", "Рецептурные"],
    therapeuticAreas: ["Широкий профиль", "Кардиология"],
    keyProducts: ["Локализованный портфель STADA"],
    hasRnD: false,
    hr: { roles: ["Производство", "QC/QA"], careerSite: "https://stada.ru/", note: "Производственная площадка STADA в Подмосковье." },
    website: "https://stada.ru/",
    logoColor: "#2563eb",
    note: ""
  },
  /* ===================== ЗАРУБЕЖНЫЕ КОМПАНИИ ===================== */
  {
    name: "Bayer",
    fullName: "Bayer AG (Германия)",
    country: "Зарубеж",
    status: "Зарубежная · с локализацией",
    hasProductionInRussia: true,
    regions: ["Москва", "Московская область"],
    factories: [
      { city: "Москва (упаковка/локализация)", lat: 55.7558, lng: 37.6173, products: "Локализация отдельных препаратов (контрактно)", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: 100000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1994,
    segments: ["Оригинальные", "Рецептурные", "OTC"],
    therapeuticAreas: ["Кардиология", "Онкология", "Гинекология", "Офтальмология"],
    keyProducts: ["Ксарелто", "Аспирин", "Мирена", "Эйлеа"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Маркетинг", "Регистрация"], careerSite: "https://www.career.bayer.ru/", note: "Локализация — преимущественно контрактное производство и упаковка." },
    website: "https://www.bayer.ru/",
    logoColor: "#16a34a",
    note: "Историко-крупнейший зарубежный игрок; в 2025 г. уступил 1 место рознице «Нижфарму»."
  },
  {
    name: "Novartis",
    fullName: "Novartis AG (Швейцария)",
    country: "Зарубеж",
    status: "Зарубежная · с локализацией",
    hasProductionInRussia: true,
    regions: ["Санкт-Петербург", "Москва"],
    factories: [
      { city: "Санкт-Петербург (Novartis Neva)", lat: 59.9500, lng: 30.3167, products: "Готовые лекарственные формы (локализация)", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: 76000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1996,
    segments: ["Оригинальные", "Рецептурные"],
    therapeuticAreas: ["Онкология", "Кардиология", "Офтальмология", "Иммунология"],
    keyProducts: ["Гилениа", "Козентикс", "Луцентис"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://www.novartis.com/careers", note: "Завод «Novartis Neva» в СПб для локализации." },
    website: "https://www.novartis.ru/",
    logoColor: "#fb923c",
    note: ""
  },
  {
    name: "Sanofi",
    fullName: "Sanofi (Франция)",
    country: "Зарубеж",
    status: "Зарубежная · с локализацией",
    hasProductionInRussia: true,
    regions: ["Орловская область"],
    factories: [
      { city: "Орёл (Санофи-Авентис Восток)", lat: 52.9685, lng: 36.0692, products: "Инсулины (локализация полного цикла)", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: 86000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1970,
    segments: ["Оригинальные", "Рецептурные", "Вакцины"],
    therapeuticAreas: ["Эндокринология (диабет)", "Иммунология", "Вакцинология"],
    keyProducts: ["Лантус", "Туджео", "Дюпиксент"],
    hasRnD: false,
    hr: { roles: ["Производство", "Медпредставители", "Регистрация"], careerSite: "https://www.sanofi.com/careers", note: "Завод в Орле — локализованное производство инсулинов." },
    website: "https://www.sanofi.ru/",
    logoColor: "#7c3aed",
    note: ""
  },
  {
    name: "KRKA",
    fullName: "KRKA d.d. (Словения)",
    country: "Зарубеж",
    status: "Зарубежная · с локализацией",
    hasProductionInRussia: true,
    regions: ["Московская область"],
    factories: [
      { city: "Истра (МО)", lat: 55.9145, lng: 36.8575, products: "Дженерики, готовые формы", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: 11000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2003,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Кардиология", "Гастроэнтерология", "Неврология"],
    keyProducts: ["Лозап", "Нольпаза", "Атакванд"],
    hasRnD: false,
    hr: { roles: ["Производство", "Медпредставители"], careerSite: "https://www.krka.biz/", note: "Завод «КРКА-РУС» в Истре." },
    website: "https://www.krka.ru/",
    logoColor: "#2563eb",
    note: ""
  },
  {
    name: "Gedeon Richter",
    fullName: "Gedeon Richter Plc. (Венгрия)",
    country: "Зарубеж",
    status: "Зарубежная · с локализацией",
    hasProductionInRussia: true,
    regions: ["Московская область"],
    factories: [
      { city: "Егорьевск (МО)", lat: 55.3833, lng: 39.0333, products: "Готовые формы, гинекология", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: 12000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1996,
    segments: ["Дженерики", "Оригинальные", "Рецептурные"],
    therapeuticAreas: ["Гинекология", "Психиатрия", "Неврология"],
    keyProducts: ["Эсмия", "Мидиана", "Кагоцел (партнёрство)"],
    hasRnD: false,
    hr: { roles: ["Производство", "Медпредставители"], careerSite: "https://www.gedeonrichter.com/", note: "Завод в Егорьевске." },
    website: "https://www.g-richter.ru/",
    logoColor: "#0891b2",
    note: ""
  },
  {
    name: "Servier",
    fullName: "Servier (Франция)",
    country: "Зарубеж",
    status: "Зарубежная · с локализацией",
    hasProductionInRussia: true,
    regions: ["Москва"],
    factories: [
      { city: "Москва (Сердикс)", lat: 55.7558, lng: 37.6173, products: "Готовые формы, кардиология", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: 22000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1992,
    segments: ["Оригинальные", "Рецептурные"],
    therapeuticAreas: ["Кардиология", "Онкология", "Диабетология"],
    keyProducts: ["Предуктал", "Диабетон", "Нолипрел"],
    hasRnD: false,
    hr: { roles: ["Производство", "Медпредставители", "Медицина"], careerSite: "https://servier.com/en/careers/", note: "Завод «Сердикс» в Москве." },
    website: "https://servier.ru/",
    logoColor: "#dc2626",
    note: "Входит в топ-10 розничного рынка РФ."
  },
  {
    name: "Takeda",
    fullName: "Takeda Pharmaceutical (Япония)",
    country: "Зарубеж",
    status: "Зарубежная · с локализацией",
    hasProductionInRussia: true,
    regions: ["Ярославская область"],
    factories: [
      { city: "Ярославль", lat: 57.6261, lng: 39.8845, products: "Готовые формы (локализация)", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: 49000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1992,
    segments: ["Оригинальные", "Рецептурные"],
    therapeuticAreas: ["Гастроэнтерология", "Онкология", "Неврология"],
    keyProducts: ["Кардиомагнил", "Актовегин", "Нольпаза"],
    hasRnD: false,
    hr: { roles: ["Производство", "Медпредставители"], careerSite: "https://www.takeda.com/careers/", note: "Завод в Ярославле." },
    website: "https://www.takeda.com/ru-ru/",
    logoColor: "#e11d48",
    note: ""
  },
  {
    name: "AstraZeneca",
    fullName: "AstraZeneca plc (Великобритания/Швеция)",
    country: "Зарубеж",
    status: "Зарубежная · с локализацией",
    hasProductionInRussia: true,
    regions: ["Калужская область"],
    factories: [
      { city: "Воробьёво (Калужская обл.)", lat: 55.1600, lng: 36.4600, products: "Готовые формы полного цикла (локализация)", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: 89000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1993,
    segments: ["Оригинальные", "Рецептурные"],
    therapeuticAreas: ["Онкология", "Кардиология", "Эндокринология (диабет)", "Пульмонология"],
    keyProducts: ["Форсига", "Тагриссо", "Симбикорт", "Крестор"],
    hasRnD: false,
    hr: { roles: ["Производство", "Медпредставители", "Медицина", "Регистрация"], careerSite: "https://careers.astrazeneca.com/", note: "Завод в Калужской области — локализация полного цикла ряда препаратов." },
    website: "https://www.astrazeneca.ru/",
    logoColor: "#7c3aed",
    note: ""
  },
  {
    name: "Novo Nordisk",
    fullName: "Novo Nordisk A/S (Дания)",
    country: "Зарубеж",
    status: "Зарубежная · с локализацией",
    hasProductionInRussia: true,
    regions: ["Калужская область"],
    factories: [
      { city: "Грабцево (Калуга)", lat: 54.5900, lng: 36.3600, products: "Инсулины (локализованное производство)", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: 64000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1923,
    segments: ["Оригинальные", "Биотех"],
    therapeuticAreas: ["Эндокринология (диабет)", "Ожирение", "Гемофилия"],
    keyProducts: ["Левемир", "НовоРапид", "Тресиба"],
    hasRnD: false,
    hr: { roles: ["Производство", "Медпредставители", "Медицина"], careerSite: "https://www.novonordisk.com/careers.html", note: "Завод по выпуску инсулинов в Калуге." },
    website: "https://www.novonordisk.ru/",
    logoColor: "#1d4ed8",
    note: ""
  },
  {
    name: "Berlin-Chemie / Menarini",
    fullName: "Berlin-Chemie AG (группа Menarini, Италия/Германия)",
    country: "Зарубеж",
    status: "Зарубежная · с локализацией",
    hasProductionInRussia: true,
    regions: ["Калужская область"],
    factories: [
      { city: "Калуга", lat: 54.5293, lng: 36.2754, products: "Готовые лекарственные формы (локализация)", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: 17000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1992,
    segments: ["Оригинальные", "Дженерики", "Рецептурные"],
    therapeuticAreas: ["Эндокринология (диабет)", "Гастроэнтерология", "Кардиология"],
    keyProducts: ["Эспумизан", "Манинил", "Мезим"],
    hasRnD: false,
    hr: { roles: ["Производство", "Медпредставители"], careerSite: "https://www.berlin-chemie.ru/", note: "Локализация в Калужской области." },
    website: "https://www.berlin-chemie.ru/",
    logoColor: "#0891b2",
    note: ""
  },
  {
    name: "Pfizer",
    fullName: "Pfizer Inc. (США)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие + локализация по контракту",
    hasProductionInRussia: true,
    regions: ["Ярославская область", "Московская область"],
    factories: [
      { city: "Ярославль (через партнёра)", lat: 57.6261, lng: 39.8845, products: "Контрактная локализация отдельных препаратов", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: 88000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1992,
    segments: ["Оригинальные", "Рецептурные", "Вакцины"],
    therapeuticAreas: ["Онкология", "Иммунология", "Вакцинология", "Кардиология"],
    keyProducts: ["Превенар 13 (локализация с Петровакс)", "Прежевалин", "Вайдуриан"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://www.pfizer.com/about/careers", note: "Локализация преимущественно по контракту с российскими партнёрами." },
    website: "https://www.pfizer.com/",
    logoColor: "#2563eb",
    note: ""
  },
  {
    name: "Teva",
    fullName: "Teva Pharmaceutical Industries (Израиль)",
    country: "Зарубеж",
    status: "Зарубежная · с локализацией",
    hasProductionInRussia: true,
    regions: ["Ярославская область"],
    factories: [
      { city: "Ярославль", lat: 57.6261, lng: 39.8845, products: "Готовые формы (завод в составе группы Р-Фарм)", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: 37000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1995,
    segments: ["Дженерики", "Оригинальные", "Рецептурные"],
    therapeuticAreas: ["Неврология", "Респираторные", "Широкий профиль"],
    keyProducts: ["Портфель дженериков Teva", "Копаксон"],
    hasRnD: false,
    hr: { roles: ["Производство", "Медпредставители"], careerSite: "https://www.tevapharm.com/careers/", note: "Ярославский завод вошёл в группу Р-Фарм." },
    website: "https://www.teva.ru/",
    logoColor: "#1d4ed8",
    note: ""
  },
  {
    name: "Sandoz",
    fullName: "Sandoz Group AG (Швейцария)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 21000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1996,
    segments: ["Дженерики", "Биотех"],
    therapeuticAreas: ["Антибиотики", "Биоаналоги", "Широкий профиль"],
    keyProducts: ["Дженерики и биосимиляры Sandoz"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Регистрация"], careerSite: "https://www.sandoz.com/careers", note: "Дженериковое подразделение, выделенное из Novartis." },
    website: "https://www.sandoz.com/",
    logoColor: "#fb923c",
    note: ""
  },
  {
    name: "Boehringer Ingelheim",
    fullName: "Boehringer Ingelheim (Германия)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 53000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1993,
    segments: ["Оригинальные", "Рецептурные"],
    therapeuticAreas: ["Эндокринология (диабет)", "Пульмонология", "Кардиология"],
    keyProducts: ["Джардинс", "Спиолто", "Прадакса"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://www.boehringer-ingelheim.com/careers", note: "Коммерческое присутствие; часть производства локализуется по контракту." },
    website: "https://www.boehringer-ingelheim.com/",
    logoColor: "#0d9488",
    note: ""
  },
  {
    name: "Johnson & Johnson",
    fullName: "Johnson & Johnson / Janssen (США)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 130000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1992,
    segments: ["Оригинальные", "Рецептурные"],
    therapeuticAreas: ["Онкология", "Иммунология", "Психиатрия", "Инфекционные"],
    keyProducts: ["Стелара", "Симпони", "Дарзалекс"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://www.careers.jnj.com/", note: "Фармподразделение Janssen; коммерческое присутствие в РФ." },
    website: "https://www.jnj.com/",
    logoColor: "#dc2626",
    note: ""
  },
  {
    name: "Roche",
    fullName: "F. Hoffmann-La Roche AG (Швейцария)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 103000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1991,
    segments: ["Оригинальные", "Биотех"],
    therapeuticAreas: ["Онкология", "Неврология", "Офтальмология", "Гематология"],
    keyProducts: ["Герцептин", "Авастин", "Окревус"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Диагностика", "Регистрация"], careerSite: "https://careers.roche.com/", note: "Лидер в онкологии; присутствие в фарме и диагностике." },
    website: "https://www.roche.ru/",
    logoColor: "#1d4ed8",
    note: ""
  },
  {
    name: "MSD",
    fullName: "Merck & Co., Inc. / MSD (США)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие + локализация по контракту",
    hasProductionInRussia: true,
    regions: ["Москва", "Московская область"],
    factories: [
      { city: "Локализация по контракту (РФ)", lat: 55.7558, lng: 37.6173, products: "Контрактная локализация отдельных препаратов", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: 71000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1991,
    segments: ["Оригинальные", "Вакцины"],
    therapeuticAreas: ["Онкология", "Вакцинология", "Инфекционные", "Кардиология"],
    keyProducts: ["Китруда", "Гардасил", "Янувия"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://jobs.merck.com/", note: "Известна как MSD за пределами США и Канады." },
    website: "https://www.msd.ru/",
    logoColor: "#0d9488",
    note: ""
  },
  {
    name: "GSK",
    fullName: "GSK plc (GlaxoSmithKline, Великобритания)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 70000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1992,
    segments: ["Оригинальные", "Вакцины", "Рецептурные"],
    therapeuticAreas: ["Пульмонология", "Вакцинология", "ВИЧ", "Иммунология"],
    keyProducts: ["Серетид", "Аугментин", "вакцины (исторически локализация с Биннофарм)"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://www.gsk.com/en-gb/careers/", note: "Часть вакцин исторически локализовалась с российскими партнёрами." },
    website: "https://www.gsk.com/",
    logoColor: "#ea580c",
    note: ""
  },
  {
    name: "Eli Lilly",
    fullName: "Eli Lilly and Company (США)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 43000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1992,
    segments: ["Оригинальные", "Биотех"],
    therapeuticAreas: ["Эндокринология (диабет/ожирение)", "Онкология", "Неврология", "Иммунология"],
    keyProducts: ["Хумалог", "Трулисити", "Тальц"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://careers.lilly.com/", note: "Коммерческое присутствие в РФ." },
    website: "https://www.lilly.com/",
    logoColor: "#dc2626",
    note: ""
  },
  {
    name: "Bristol Myers Squibb",
    fullName: "Bristol Myers Squibb (США)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 34000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1992,
    segments: ["Оригинальные", "Биотех"],
    therapeuticAreas: ["Онкология", "Гематология", "Иммунология", "Кардиология"],
    keyProducts: ["Опдиво", "Эликвис", "Ревлимид"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://careers.bms.com/", note: "Коммерческое присутствие; сильная онкологическая линейка." },
    website: "https://www.bms.com/",
    logoColor: "#2563eb",
    note: ""
  },
  {
    name: "AbbVie",
    fullName: "AbbVie Inc. (США)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 50000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2013,
    segments: ["Оригинальные", "Биотех"],
    therapeuticAreas: ["Иммунология", "Онкология", "Гастроэнтерология", "Неврология"],
    keyProducts: ["Хумира", "Скайризи", "Ринвок"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://careers.abbvie.com/", note: "Выделена из Abbott в 2013 г." },
    website: "https://www.abbvie.com/",
    logoColor: "#0369a1",
    note: ""
  },
  {
    name: "Amgen",
    fullName: "Amgen Inc. (США)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 28000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2011,
    segments: ["Биотех", "Оригинальные"],
    therapeuticAreas: ["Онкология", "Кардиология", "Остеология", "Гематология"],
    keyProducts: ["Пролиа", "Эксджива", "Репата"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://careers.amgen.com/", note: "Один из крупнейших мировых биотех-производителей." },
    website: "https://www.amgen.com/",
    logoColor: "#1d4ed8",
    note: ""
  },
  {
    name: "Merck KGaA",
    fullName: "Merck KGaA (Германия)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 63000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1992,
    segments: ["Оригинальные", "Рецептурные"],
    therapeuticAreas: ["Эндокринология", "Онкология", "Неврология", "Репродукция"],
    keyProducts: ["Эутирокс", "Конкор", "Гонал-Ф"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://www.merckgroup.com/en/careers.html", note: "Старейшая фармкомпания мира (немецкая Merck, отдельно от MSD)." },
    website: "https://www.merckgroup.com/",
    logoColor: "#7c3aed",
    note: ""
  },
  {
    name: "Fresenius Kabi",
    fullName: "Fresenius Kabi AG (Германия)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 42000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1996,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Клиническое питание", "Инфузионная терапия", "Онкология"],
    keyProducts: ["Растворы для инфузий", "Парентеральное питание", "Онкодженерики"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Логистика", "Регистрация"], careerSite: "https://www.fresenius-kabi.com/careers", note: "Лидер в инфузионной терапии и клиническом питании." },
    website: "https://www.fresenius-kabi.com/",
    logoColor: "#0d9488",
    note: ""
  },
  {
    name: "B. Braun",
    fullName: "B. Braun SE (Германия)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва", "Санкт-Петербург"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 66000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1993,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Инфузионная терапия", "Хирургия", "Нефрология (диализ)"],
    keyProducts: ["Растворы для инфузий", "Антисептики (Пронтосан)", "Медизделия"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Логистика", "Сервис"], careerSite: "https://www.bbraun.com/en/career.html", note: "Препараты и медицинские изделия для стационаров." },
    website: "https://www.bbraun.ru/",
    logoColor: "#16a34a",
    note: ""
  },
  {
    name: "Recordati",
    fullName: "Recordati S.p.A. (Италия)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 4500,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2008,
    segments: ["Оригинальные", "Рецептурные", "OTC"],
    therapeuticAreas: ["Урология", "Орфанные заболевания", "Кардиология"],
    keyProducts: ["Урорек", "Орфанные препараты"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Регистрация"], careerSite: "https://www.recordati.com/en/careers/", note: "Специализация на орфанных и урологических препаратах." },
    website: "https://www.recordati.com/",
    logoColor: "#dc2626",
    note: ""
  },
  {
    name: "Egis",
    fullName: "Egis Pharmaceuticals PLC (Венгрия, группа Servier)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 5500,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1994,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Кардиология", "Неврология", "Психиатрия"],
    keyProducts: ["Эгилок", "Грандаксин", "Бетасерк"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Регистрация"], careerSite: "https://www.egis.health/", note: "Входит в группу Servier." },
    website: "https://www.egis.ru/",
    logoColor: "#b91c1c",
    note: ""
  },
  {
    name: "Adamed",
    fullName: "Adamed Pharma S.A. (Польша)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 2500,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2013,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Кардиология", "Неврология", "Широкий профиль"],
    keyProducts: ["Портфель дженериков Adamed"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Регистрация"], careerSite: "https://www.adamed.com/en/career", note: "" },
    website: "https://www.adamed.com/",
    logoColor: "#0891b2",
    note: ""
  },
  {
    name: "Hemofarm (STADA)",
    fullName: "Hemofarm A.D. (Сербия, группа STADA)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 5000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2006,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Кардиология", "Неврология", "Широкий профиль"],
    keyProducts: ["Портфель дженериков Hemofarm"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Регистрация"], careerSite: "https://www.hemofarm.com/", note: "Сербский производитель в составе STADA; локализация через «Нижфарм»." },
    website: "https://www.hemofarm.com/",
    logoColor: "#2563eb",
    note: ""
  },
  {
    name: "Acino",
    fullName: "Acino International AG (Швейцария)",
    country: "Зарубеж",
    status: "Зарубежная · с локализацией по контракту",
    hasProductionInRussia: true,
    regions: ["Москва", "Московская область"],
    factories: [
      { city: "Локализация по контракту (РФ)", lat: 55.7558, lng: 37.6173, products: "Контрактная локализация готовых форм", gmp: "Да" }
    ],
    employeesRussia: "н/д",
    employeesGlobal: 3000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2014,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Кардиология", "Неврология", "ЦНС"],
    keyProducts: ["Трансдермальные системы", "Кардио- и ЦНС-дженерики"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Регистрация", "Производство (контракт)"], careerSite: "https://acino.swiss/career/", note: "Локализация через контрактных партнёров в РФ." },
    website: "https://acino.swiss/",
    logoColor: "#dc2626",
    note: ""
  },
  {
    name: "Zentiva",
    fullName: "Zentiva k.s. (Чехия)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 5000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2009,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Кардиология", "ЦНС", "Широкий профиль"],
    keyProducts: ["Портфель дженериков Zentiva"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Регистрация"], careerSite: "https://www.zentiva.com/careers", note: "Бывшее дженериковое подразделение Sanofi в Центральной Европе." },
    website: "https://www.zentiva.com/",
    logoColor: "#ea580c",
    note: ""
  },
  {
    name: "Viatris",
    fullName: "Viatris Inc. (Mylan, США)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 38000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2007,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["ВИЧ", "Кардиология", "Неврология", "Широкий профиль"],
    keyProducts: ["Портфель дженериков", "Антиретровирусные"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Регистрация"], careerSite: "https://www.viatris.com/en/careers", note: "Образована слиянием Mylan и Upjohn (Pfizer)." },
    website: "https://www.viatris.com/",
    logoColor: "#0369a1",
    note: ""
  },
  {
    name: "Hikma",
    fullName: "Hikma Pharmaceuticals PLC (Иордания/Великобритания)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 9000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2015,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Госпитальный сегмент", "Онкология", "Широкий профиль"],
    keyProducts: ["Инъекционные и госпитальные дженерики"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Регистрация"], careerSite: "https://www.hikma.com/careers/", note: "" },
    website: "https://www.hikma.com/",
    logoColor: "#16a34a",
    note: ""
  },
  {
    name: "Cipla",
    fullName: "Cipla Limited (Индия)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 25000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2010,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Пульмонология", "ВИЧ", "Онкология"],
    keyProducts: ["Ингаляционные препараты", "Антиретровирусные дженерики"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Регистрация"], careerSite: "https://www.cipla.com/careers", note: "Один из крупнейших индийских производителей." },
    website: "https://www.cipla.com/",
    logoColor: "#0891b2",
    note: ""
  },
  {
    name: "Aurobindo",
    fullName: "Aurobindo Pharma Limited (Индия)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 27000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2012,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Антибиотики", "Кардиология", "Широкий профиль"],
    keyProducts: ["Антибиотики и широкий портфель дженериков"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Регистрация"], careerSite: "https://www.aurobindo.com/careers/", note: "" },
    website: "https://www.aurobindo.com/",
    logoColor: "#7c3aed",
    note: ""
  },
  {
    name: "Glenmark",
    fullName: "Glenmark Pharmaceuticals Ltd. (Индия)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 14000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2009,
    segments: ["Дженерики", "Рецептурные", "OTC"],
    therapeuticAreas: ["Дерматология", "Пульмонология", "Широкий профиль"],
    keyProducts: ["Момат", "Кандидерм", "Аскорил"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Регистрация"], careerSite: "https://www.glenmarkpharma.com/careers", note: "Известна препаратами в дерматологии и респираторике." },
    website: "https://www.glenmarkpharma.com/",
    logoColor: "#dc2626",
    note: ""
  },
  {
    name: "Dr. Reddy's",
    fullName: "Dr. Reddy's Laboratories Ltd. (Индия)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 25000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1992,
    segments: ["Дженерики", "Рецептурные"],
    therapeuticAreas: ["Гастроэнтерология", "Онкология", "Широкий профиль"],
    keyProducts: ["Найз", "Омез", "Кетонал"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Регистрация"], careerSite: "https://careers.drreddys.com/", note: "Один из старейших индийских игроков на рынке РФ." },
    website: "https://www.drreddys.com/",
    logoColor: "#0369a1",
    note: ""
  },
  {
    name: "Astellas",
    fullName: "Astellas Pharma Inc. (Япония)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 14000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1994,
    segments: ["Оригинальные", "Рецептурные"],
    therapeuticAreas: ["Онкология", "Урология", "Трансплантология"],
    keyProducts: ["Кстанди", "Везикар", "Програф"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://www.astellas.com/en/careers", note: "" },
    website: "https://www.astellas.com/",
    logoColor: "#be123c",
    note: ""
  },
  {
    name: "Daiichi Sankyo",
    fullName: "Daiichi Sankyo Co., Ltd. (Япония)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 18000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2008,
    segments: ["Оригинальные", "Рецептурные"],
    therapeuticAreas: ["Кардиология", "Онкология"],
    keyProducts: ["Олмесартан", "Энхерту"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://www.daiichisankyo.com/careers/", note: "" },
    website: "https://www.daiichisankyo.com/",
    logoColor: "#dc2626",
    note: ""
  },
  {
    name: "Pierre Fabre",
    fullName: "Pierre Fabre Group (Франция)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 10000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1996,
    segments: ["Оригинальные", "OTC"],
    therapeuticAreas: ["Дерматология", "Онкология", "Дермокосметика"],
    keyProducts: ["Avène", "Ducray", "онкопрепараты"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Маркетинг", "Регистрация"], careerSite: "https://www.pierre-fabre.com/en/careers", note: "Известна дермокосметикой (Avène) и онкологией." },
    website: "https://www.pierre-fabre.com/",
    logoColor: "#0d9488",
    note: ""
  },
  {
    name: "Chiesi",
    fullName: "Chiesi Farmaceutici S.p.A. (Италия)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 7000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2008,
    segments: ["Оригинальные", "Рецептурные"],
    therapeuticAreas: ["Пульмонология", "Неонатология", "Орфанные заболевания"],
    keyProducts: ["Фостер", "Куросурф"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://www.chiesi.com/en/careers/", note: "" },
    website: "https://www.chiesi.com/",
    logoColor: "#0891b2",
    note: ""
  },
  {
    name: "Ferring",
    fullName: "Ferring Pharmaceuticals (Швейцария)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 7000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1996,
    segments: ["Оригинальные", "Рецептурные"],
    therapeuticAreas: ["Репродуктивное здоровье", "Урология", "Гастроэнтерология"],
    keyProducts: ["Менопур", "Пентаса", "Минирин"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://www.ferring.com/careers/", note: "" },
    website: "https://www.ferring.com/",
    logoColor: "#1d4ed8",
    note: ""
  },
  {
    name: "Ipsen",
    fullName: "Ipsen S.A. (Франция)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 5700,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1996,
    segments: ["Оригинальные", "Рецептурные"],
    therapeuticAreas: ["Онкология", "Неврология", "Эндокринология"],
    keyProducts: ["Диспорт", "Соматулин", "Декапептил"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://www.ipsen.com/careers/", note: "" },
    website: "https://www.ipsen.com/",
    logoColor: "#9333ea",
    note: ""
  },
  {
    name: "Lundbeck",
    fullName: "H. Lundbeck A/S (Дания)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 5600,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 1995,
    segments: ["Оригинальные", "Рецептурные"],
    therapeuticAreas: ["Психиатрия", "Неврология"],
    keyProducts: ["Бринтелликс", "Ципралекс", "Азилект"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://www.lundbeck.com/global/careers", note: "Специализация только на заболеваниях ЦНС." },
    website: "https://www.lundbeck.com/",
    logoColor: "#0369a1",
    note: ""
  },
  {
    name: "Gilead Sciences",
    fullName: "Gilead Sciences, Inc. (США)",
    country: "Зарубеж",
    status: "Зарубежная · присутствие",
    hasProductionInRussia: false,
    regions: ["Москва"],
    factories: [],
    employeesRussia: "н/д",
    employeesGlobal: 18000,
    revenue: null,
    revenueYear: 2025,
    yearEnteredRussia: 2015,
    segments: ["Оригинальные", "Биотех"],
    therapeuticAreas: ["ВИЧ", "Гепатиты", "Онкология"],
    keyProducts: ["Биктарви", "Совальди", "Эпклюза"],
    hasRnD: false,
    hr: { roles: ["Медпредставители", "Медицина", "Регистрация"], careerSite: "https://www.gilead.com/careers", note: "Лидер в терапии ВИЧ и вирусных гепатитов." },
    website: "https://www.gilead.com/",
    logoColor: "#be123c",
    note: ""
  }
];
